create extension if not exists pgcrypto;

create table if not exists public.departments (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  short_name text not null,
  programs text[] not null default '{}',
  created_at timestamptz not null default now()
);

alter table public.departments add column if not exists programs text[] not null default '{}';

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  employee_id text unique,
  full_name text not null,
  first_name text,
  last_name text,
  username text unique not null,
  email text unique not null,
  role text not null check (role in ('super_admin', 'department_admin', 'staff')),
  phone text,
  department_id uuid references public.departments(id) on delete set null,
  position text,
  status text not null default 'active' check (status in ('active', 'inactive')),
  profile_picture_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  contact_person text,
  phone text,
  email text,
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.facilities (
  id bigint generated by default as identity primary key,
  name text not null,
  facility_type text not null,
  department_id uuid references public.departments(id) on delete set null,
  capacity integer not null default 0,
  current_availability text not null default 'available' check (current_availability in ('available', 'reserved', 'in_use', 'under_maintenance')),
  assigned_equipment_count integer not null default 0,
  maintenance_history_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.equipment (
  id bigint generated by default as identity primary key,
  equipment_code text not null unique,
  equipment_name text not null,
  description text,
  category_id bigint references public.categories(id) on delete set null,
  category text,
  status text not null default 'available' check (status in ('available', 'borrowed', 'maintenance', 'damaged', 'lost', 'disposed')),
  location text,
  department_id uuid references public.departments(id) on delete set null,
  facility_id bigint references public.facilities(id) on delete set null,
  assigned_room text,
  condition text,
  quantity integer not null default 1,
  unit text,
  purchase_date date,
  value numeric(10,2),
  supplier_id bigint references public.suppliers(id) on delete set null,
  supplier text,
  qr_path text,
  item_photo text,
  remarks text,
  qr_code bytea,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.qr_codes (
  id bigint generated by default as identity primary key,
  equipment_id bigint not null unique references public.equipment(id) on delete cascade,
  qr_code_data text,
  qr_image_path text,
  created_at timestamptz not null default now()
);

create table if not exists public.borrow_records (
  id bigint generated by default as identity primary key,
  equipment_id bigint not null references public.equipment(id) on delete cascade,
  borrower_id uuid not null references public.profiles(id) on delete cascade,
  created_by uuid references public.profiles(id) on delete set null,
  approved_by uuid references public.profiles(id) on delete set null,
  department_id uuid references public.departments(id) on delete set null,
  borrowed_date timestamptz not null default now(),
  expected_return_date timestamptz,
  actual_return_date timestamptz,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'borrowed', 'return_requested', 'returned', 'overdue')),
  condition_before text,
  condition_after text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.maintenance_requests (
  id bigint generated by default as identity primary key,
  department_id uuid references public.departments(id) on delete set null,
  equipment_id bigint references public.equipment(id) on delete set null,
  facility_id bigint references public.facilities(id) on delete set null,
  requester_id uuid references public.profiles(id) on delete set null,
  assigned_to_id uuid references public.profiles(id) on delete set null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'in_progress', 'completed', 'rejected')),
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high', 'critical')),
  description text,
  requested_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete cascade,
  department_id uuid references public.departments(id) on delete cascade,
  title text not null,
  message text not null,
  tone text not null default 'info' check (tone in ('info', 'warning', 'success', 'danger')),
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id bigint,
  old_values jsonb,
  new_values jsonb,
  description text,
  ip_address text,
  created_at timestamptz not null default now()
);

create table if not exists public.login_logs (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles(id) on delete cascade,
  role text,
  event text not null,
  ip_address text,
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.current_user_department_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select department_id from public.profiles where id = auth.uid();
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_user_role() = 'super_admin';
$$;

create or replace function public.is_department_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_user_role() = 'department_admin';
$$;

-- Auto-create a profile row (role 'staff', status 'inactive') whenever a new
-- auth.users row is created, so the register flow never has to insert into
-- profiles directly. security definer + owned by postgres so it bypasses RLS.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  is_trusted boolean := auth.role() = 'service_role';
begin
  -- role/status only ever come from metadata when the auth.users row was
  -- created via the service-role Admin API (trusted, e.g. the demo-account
  -- seed script) — never from a self-service signUp() call, or any visitor
  -- could hand themselves 'super_admin' + 'active' in their own request body.
  insert into public.profiles (id, full_name, username, email, role, status, department_id, position, employee_id)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.email),
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    new.email,
    case when is_trusted then coalesce(new.raw_user_meta_data->>'role', 'staff') else 'staff' end,
    case when is_trusted then coalesce(new.raw_user_meta_data->>'status', 'inactive') else 'inactive' end,
    nullif(new.raw_user_meta_data->>'department_id', '')::uuid,
    new.raw_user_meta_data->>'position',
    nullif(new.raw_user_meta_data->>'employee_id', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- Lets the login screen resolve "username or email" to an email address
-- before a session exists (RLS on profiles requires auth.uid(), which isn't
-- set yet at login time). Only returns the email for a given username, not
-- any other profile data.
create or replace function public.email_for_username(lookup_username text)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select email from public.profiles where username = lookup_username limit 1;
$$;

grant execute on function public.email_for_username(text) to anon, authenticated;

-- RLS row policies control *which rows* a user can update; this trigger
-- controls *which columns*, so a self-registered user (or a department
-- admin updating their own staff) can't grant themselves a higher role,
-- flip their own status to active, or move themselves to another department.
create or replace function public.protect_profile_privileges()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.role() = 'service_role' or public.is_super_admin() then
    return new;
  end if;

  if public.is_department_admin() and old.department_id = public.current_user_department_id() then
    new.role := old.role;
    new.department_id := old.department_id;
    return new;
  end if;

  new.role := old.role;
  new.status := old.status;
  new.department_id := old.department_id;
  return new;
end;
$$;

drop trigger if exists trg_profiles_protect_privileges on public.profiles;
create trigger trg_profiles_protect_privileges
before update on public.profiles
for each row execute function public.protect_profile_privileges();

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists trg_equipment_updated_at on public.equipment;
create trigger trg_equipment_updated_at
before update on public.equipment
for each row execute function public.touch_updated_at();

drop trigger if exists trg_facilities_updated_at on public.facilities;
create trigger trg_facilities_updated_at
before update on public.facilities
for each row execute function public.touch_updated_at();

drop trigger if exists trg_borrow_records_updated_at on public.borrow_records;
create trigger trg_borrow_records_updated_at
before update on public.borrow_records
for each row execute function public.touch_updated_at();

drop trigger if exists trg_maintenance_requests_updated_at on public.maintenance_requests;
create trigger trg_maintenance_requests_updated_at
before update on public.maintenance_requests
for each row execute function public.touch_updated_at();

alter table public.departments enable row level security;
alter table public.profiles enable row level security;
alter table public.suppliers enable row level security;
alter table public.categories enable row level security;
alter table public.facilities enable row level security;
alter table public.equipment enable row level security;
alter table public.qr_codes enable row level security;
alter table public.borrow_records enable row level security;
alter table public.maintenance_requests enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_logs enable row level security;
alter table public.login_logs enable row level security;

drop policy if exists "public read departments" on public.departments;
create policy "public read departments"
on public.departments
for select
to authenticated
using (true);

drop policy if exists "profiles select own or admin" on public.profiles;
create policy "profiles select own or admin"
on public.profiles
for select
to authenticated
using (id = auth.uid() or public.is_super_admin() or (public.is_department_admin() and department_id = public.current_user_department_id()));

drop policy if exists "profiles insert admin only" on public.profiles;
create policy "profiles insert admin only"
on public.profiles
for insert
to authenticated
with check (public.is_super_admin());

drop policy if exists "profiles update own or admin" on public.profiles;
create policy "profiles update own or admin"
on public.profiles
for update
to authenticated
using (id = auth.uid() or public.is_super_admin() or (public.is_department_admin() and department_id = public.current_user_department_id()))
with check (id = auth.uid() or public.is_super_admin() or (public.is_department_admin() and department_id = public.current_user_department_id()));

drop policy if exists "departments admin write" on public.departments;
create policy "departments admin write"
on public.departments
for all
to authenticated
using (public.is_super_admin())
with check (public.is_super_admin());

drop policy if exists "lookup tables readable" on public.suppliers;
create policy "lookup tables readable"
on public.suppliers
for select
to authenticated
using (true);

drop policy if exists "suppliers admin write" on public.suppliers;
create policy "suppliers admin write"
on public.suppliers
for all
to authenticated
using (public.is_super_admin())
with check (public.is_super_admin());

drop policy if exists "lookup tables readable categories" on public.categories;
create policy "lookup tables readable categories"
on public.categories
for select
to authenticated
using (true);

drop policy if exists "categories admin write" on public.categories;
create policy "categories admin write"
on public.categories
for all
to authenticated
using (public.is_super_admin())
with check (public.is_super_admin());

drop policy if exists "facilities scoped select" on public.facilities;
create policy "facilities scoped select"
on public.facilities
for select
to authenticated
using (public.is_super_admin() or department_id = public.current_user_department_id());

drop policy if exists "facilities admin write" on public.facilities;
create policy "facilities admin write"
on public.facilities
for all
to authenticated
using (public.is_super_admin() or (public.is_department_admin() and department_id = public.current_user_department_id()))
with check (public.is_super_admin() or (public.is_department_admin() and department_id = public.current_user_department_id()));

drop policy if exists "equipment scoped select" on public.equipment;
create policy "equipment scoped select"
on public.equipment
for select
to authenticated
using (public.is_super_admin() or department_id = public.current_user_department_id());

drop policy if exists "equipment admin write" on public.equipment;
create policy "equipment admin write"
on public.equipment
for all
to authenticated
using (public.is_super_admin() or (public.is_department_admin() and department_id = public.current_user_department_id()))
with check (public.is_super_admin() or (public.is_department_admin() and department_id = public.current_user_department_id()));

drop policy if exists "qr codes scoped select" on public.qr_codes;
create policy "qr codes scoped select"
on public.qr_codes
for select
to authenticated
using (exists (
  select 1
  from public.equipment equipment_row
  where equipment_row.id = qr_codes.equipment_id
    and (public.is_super_admin() or equipment_row.department_id = public.current_user_department_id())
));

drop policy if exists "qr codes admin write" on public.qr_codes;
create policy "qr codes admin write"
on public.qr_codes
for all
to authenticated
using (public.is_super_admin())
with check (public.is_super_admin());

drop policy if exists "borrow select scoped" on public.borrow_records;
create policy "borrow select scoped"
on public.borrow_records
for select
to authenticated
using (public.is_super_admin() or department_id = public.current_user_department_id() or borrower_id = auth.uid());

drop policy if exists "borrow insert scoped" on public.borrow_records;
create policy "borrow insert scoped"
on public.borrow_records
for insert
to authenticated
with check (borrower_id = auth.uid() or public.is_department_admin() or public.is_super_admin());

drop policy if exists "borrow update scoped" on public.borrow_records;
create policy "borrow update scoped"
on public.borrow_records
for update
to authenticated
using (public.is_super_admin() or public.is_department_admin() or borrower_id = auth.uid())
with check (public.is_super_admin() or public.is_department_admin() or borrower_id = auth.uid());

drop policy if exists "maintenance select scoped" on public.maintenance_requests;
create policy "maintenance select scoped"
on public.maintenance_requests
for select
to authenticated
using (public.is_super_admin() or department_id = public.current_user_department_id() or requester_id = auth.uid());

drop policy if exists "maintenance write scoped" on public.maintenance_requests;
create policy "maintenance write scoped"
on public.maintenance_requests
for all
to authenticated
using (public.is_super_admin() or public.is_department_admin() or requester_id = auth.uid())
with check (public.is_super_admin() or public.is_department_admin() or requester_id = auth.uid());

drop policy if exists "notifications scoped select" on public.notifications;
create policy "notifications scoped select"
on public.notifications
for select
to authenticated
using (profile_id = auth.uid() or department_id = public.current_user_department_id() or public.is_super_admin());

drop policy if exists "audit logs admin only" on public.audit_logs;
create policy "audit logs admin only"
on public.audit_logs
for select
to authenticated
using (public.is_super_admin());

drop policy if exists "login logs admin only" on public.login_logs;
create policy "login logs admin only"
on public.login_logs
for select
to authenticated
using (public.is_super_admin());

insert into public.departments (name, short_name, programs)
values
  ('College of Teacher Education', 'Teacher Education', array['BEEd', 'BSEd Math', 'BSEd English']),
  ('College of Industrial Technology', 'Industrial Technology', array['BSIT Electrical', 'BSIT Food Prep']),
  ('College of Fisheries', 'Fisheries', array['BS Fisheries']),
  ('Department of Computer Science', 'Computer Science', array['BS Computer Science'])
on conflict (name) do update set short_name = excluded.short_name, programs = excluded.programs;
