-- Facility reservations: staff, department admins (deans), and super admins can
-- request the use of an available facility for a dated time window. Requests
-- start 'pending' and are approved/rejected by the facility's department admin
-- or a super admin. Students do not reserve facilities (they only borrow items).
--
-- This reuses the existing RLS helpers (is_super_admin / is_department_admin /
-- current_user_department_id) and the department-scoped notifications table, so
-- no edge function is required — row policies plus a status-guard trigger enforce
-- the whole rule set server-side.

create table if not exists public.facility_reservations (
  id bigint generated by default as identity primary key,
  facility_id bigint not null references public.facilities(id) on delete cascade,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  department_id uuid references public.departments(id) on delete set null,
  reserved_date date not null,
  start_time time not null,
  end_time time not null,
  purpose text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'cancelled')),
  approved_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint facility_reservations_time_order check (end_time > start_time)
);

create index if not exists idx_facility_reservations_facility on public.facility_reservations(facility_id);
create index if not exists idx_facility_reservations_status on public.facility_reservations(status);

drop trigger if exists trg_facility_reservations_updated_at on public.facility_reservations;
create trigger trg_facility_reservations_updated_at
before update on public.facility_reservations
for each row execute function public.touch_updated_at();

-- RLS controls *which rows* a caller may touch; this trigger controls *which
-- status transitions* they may make, so a plain requester can't self-approve by
-- calling update directly (their row passes the update policy via requester_id).
create or replace function public.guard_facility_reservation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  is_admin boolean := public.is_super_admin()
    or (public.is_department_admin() and old.department_id is not distinct from public.current_user_department_id());
begin
  if auth.role() = 'service_role' or is_admin then
    return new;
  end if;

  -- The requester may only cancel their own still-pending request.
  if new.status is distinct from old.status
     and not (old.status = 'pending' and new.status = 'cancelled') then
    raise exception 'Only an administrator can change a reservation to %', new.status;
  end if;

  -- Non-admins can never stamp themselves as the approver.
  new.approved_by := old.approved_by;
  return new;
end;
$$;

drop trigger if exists trg_facility_reservations_guard on public.facility_reservations;
create trigger trg_facility_reservations_guard
before update on public.facility_reservations
for each row execute function public.guard_facility_reservation();

-- Notify the facility's department (dean; super admins can read every
-- notification) on a new request, and notify the requester on approve/reject.
create or replace function public.notify_facility_reservation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.notifications (department_id, title, message, tone)
    values (
      new.department_id,
      'New facility reservation',
      'A facility reservation request for ' || new.reserved_date || ' is awaiting review.',
      'info'
    );
  elsif tg_op = 'UPDATE'
        and new.status is distinct from old.status
        and new.status in ('approved', 'rejected') then
    insert into public.notifications (profile_id, title, message, tone)
    values (
      new.requester_id,
      'Facility reservation ' || new.status,
      'Your facility reservation for ' || new.reserved_date || ' was ' || new.status || '.',
      case when new.status = 'approved' then 'success' else 'danger' end
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_facility_reservations_notify_insert on public.facility_reservations;
create trigger trg_facility_reservations_notify_insert
after insert on public.facility_reservations
for each row execute function public.notify_facility_reservation();

drop trigger if exists trg_facility_reservations_notify_update on public.facility_reservations;
create trigger trg_facility_reservations_notify_update
after update on public.facility_reservations
for each row execute function public.notify_facility_reservation();

alter table public.facility_reservations enable row level security;

drop policy if exists "facility reservations select scoped" on public.facility_reservations;
create policy "facility reservations select scoped"
on public.facility_reservations
for select
to authenticated
using (public.is_super_admin() or department_id = public.current_user_department_id() or requester_id = auth.uid());

-- Any non-student may file a request, but only for themselves and only as
-- 'pending' — the status guard trigger governs every transition after that.
drop policy if exists "facility reservations insert own" on public.facility_reservations;
create policy "facility reservations insert own"
on public.facility_reservations
for insert
to authenticated
with check (requester_id = auth.uid() and public.current_user_role() <> 'student' and status = 'pending');

drop policy if exists "facility reservations update scoped" on public.facility_reservations;
create policy "facility reservations update scoped"
on public.facility_reservations
for update
to authenticated
using (
  public.is_super_admin()
  or (public.is_department_admin() and department_id = public.current_user_department_id())
  or requester_id = auth.uid()
)
with check (
  public.is_super_admin()
  or (public.is_department_admin() and department_id = public.current_user_department_id())
  or requester_id = auth.uid()
);
